services:

  web:
    build: .
    command: ["../wait-for-it.sh"]
    restart: always
    working_dir: /code/educa 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - db
      - cache

  db:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379

  daphne:
    build: .
    working_dir: /code/educa/
    command: ["../wait-for-it.sh"] 
    restart: always
    volumes:
      - .:/code
    expose:
      - "9001"
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - START_DAPHNE=true
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:1.25.5-alpine
    restart: always
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/code
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - daphne
    networks:
      - default

