# Generated by Django 5.2.7 on 2025-10-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
